/*========================================================================*
 * NI VeriStand Model Framework code generation
 *
 * Model : simplePathFollow
 * Model version : 1.40
 * VeriStand Model Framework version : 2020.2.0.0 (2020 R2)
 * Source generated on : Tue Oct 20 03:39:32 2020
 *========================================================================*/

/*
 * Note:
 *   This file was generated by the main model, simplePathFollow.
 *   This file redirects parameter references to the NI VeriStand rtParameter buffer.
 *
 *   In a model reference configuration, this file defines the globally shared parameter structure
 *   across all model references. All models must share the same type definition for proper execution.
 *
 */
#if !defined(_DEFINED_TYPEDEF_FOR_niUrtParametersTypeDef_)
#define _DEFINED_TYPEDEF_FOR_niUrtParametersTypeDef_
#include "simplePathFollow_types.h"

/* Parameters typedef identifier */
#define NI_PARAM_TYPEDEF               P_simplePathFollow_T
#endif

#if defined(_NI_DEFINE_PARAMS_DBL_BUFFER_)
#undef _NI_DEFINE_PARAMS_DBL_BUFFER_
#ifdef MULTITASKING
#define NI_PARAM_BUFF                  (*param_lookup[tid][READSIDE])
#else
#define NI_PARAM_BUFF                  rtParameter[READSIDE]
#endif

#define simplePathFollow_P             NI_PARAM_BUFF
#elif defined(_NI_UNDEFINE_PARAMS_DBL_BUFFER_)
#undef _NI_UNDEFINE_PARAMS_DBL_BUFFER_
#undef simplePathFollow_P
#endif
